spring.application.name=Deckforge
spring.datasource.url=jdbc:mysql://localhost:3306/Deckforge
spring.datasource.username=root
spring.datasource.password=Root.1234
spring.datasource.driver-class-name=com.mysql.cj.jdbc.Driver

spring.sql.init.mode=always

spring.thymeleaf.cache=false

server.port=8080
server.address=0.0.0.0

logging.level.root=INFO
logging.level.org.example.deckforge=DEBUG
spring.web.error.include-message=always
spring.web.error.include-stacktrace=always
spring.web.error.include-exception=true

